### ISSUE TITLE
vendor/autoload.php missing from package

### ISSUE THREAD

**Issue by madesimplemedia** [concrete5-community-store/community_store_stripe#1]
When I add the package to the packages folder I get an error saying this is missing.

**Comment by Mesuva** [comment]
This package requires you to run composer on the package before installing it.

**Comment by madesimplemedia** [comment]
OK, I will do that, thanks for the info.

**Comment by typoman76** [comment]
Is there a tutorial ho to install something with composer. Is there a way of installing it on a shared-hosting with no access to command line? I'm not familiar with composer at all.

**Comment by typoman76** [comment]
I got it with composer... Thanks for making this package available.
