### ISSUE TITLE
Critical Error on Install

### ISSUE THREAD

**Issue by drumrby** [concrete5-community-store/community_store_stripe#13]
I tried installing the ZIP today and got this error:

Concrete\Package\CommunityStoreStripe\Controller::on_start(): Failed opening required 'www/packages/community_store_stripe/vendor/autoload.php' (include_path='www/updates/concrete5-8.3.2/concrete/vendor:.:/usr/share/php')

Hadn't seen this before and didn't seem like one that had been previously reported. Any help provided would be greatly appreciated.

**Comment by Mesuva** [comment]
That looks like the vendor libraries aren't in place - which is solved by running composer install.
However, if you've downloaded a release zip you shouldn't be expected to do that. 

It looks like the previous releases didn't include the libraries... 

So try this one instead:
https://github.com/concrete5-community-store/community_store_stripe/releases/tag/v1.0.7

**Comment by drumrby** [comment]
That worked. Thank you!
