### ISSUE TITLE
Error on install: on_start event

### ISSUE THREAD

**Issue by dbuonomo** [concrete5-community-store/community_store_stripe#3]
Attempting to install community_store_stripe on concrete5 v8, the following error occured:

Concrete\Package\CommunityStoreStripe\Controller::on_start(): Failed opening required 'vendor/autoload.php' (include_path='/var/www/c5.8/concrete/vendor:.:/usr/share/php:/usr/share/pear')

The repository was cloned in the packages folder as follows: 

git clone git@github.com:concrete5-community-store/community_store_stripe.git

Write privileges are enabled for the apache process on the community_store_stripe directory.

**Comment by Remo** [comment]
Check the README https://github.com/concrete5-community-store/community_store_stripe

>  This add-on uses Composer to install third-party librares. Run composer at the root of the add-on folder    before installing:
>
>        composer install

**Comment by dbuonomo** [comment]
Just noticed that after posting. Thanks.

**Comment by Mesuva** [comment]
There is also a release zip available, which includes the vendor libraries,
ready to run. 1.0.1 was added today.
