### ISSUE TITLE
error installing on concrete5.7.5.8, php 5.6

### ISSUE THREAD

**Issue by jalen-seguin** [concrete5-community-store/community_store_stripe#4]
I've followed the instructions, and used composer to install.  I got the following feedback:

[ps382647]$ php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing stripe/stripe-php (v4.3.0): Downloading (100%)         
Generating autoload files

Then I attempted to activate/install the community_store_stripe package in the Dashboard/Extend concrete5 area, but I got the following error:

"Call to a member function getPackageHandle() on null"

This error doesn't lock me out of using the site, but I do get this message every time I go to the Dashboard/Store/Settings area.

Any and all help is greatly appreciated.

Thanks,

~ Jalen.

See below for my environment settings..

# concrete5 Version
Core Version - 5.7.5.8
Version Installed - 5.7.5.8
Database Version - 20160412000000

# concrete5 Packages
Community Store (1.1.3), Stripe Payment Method (1.0.3).

# concrete5 Overrides
languages/cs_CZ/LC_MESSAGES/messages.mo, languages/cs_CZ/LC_MESSAGES, languages/cs_CZ, languages/da_DK/LC_MESSAGES/messages.mo, languages/da_DK/LC_MESSAGES, languages/da_DK, languages/de_DE/LC_MESSAGES/messages.mo, languages/de_DE/LC_MESSAGES, languages/de_DE, languages/el_GR/LC_MESSAGES/messages.mo, languages/el_GR/LC_MESSAGES, languages/el_GR, languages/es_PY/LC_MESSAGES/messages.mo, languages/es_PY/LC_MESSAGES, languages/es_PY, languages/fi_FI/LC_MESSAGES/messages.mo, languages/fi_FI/LC_MESSAGES, languages/fi_FI, languages/fr_FR/LC_MESSAGES/messages.mo, languages/fr_FR/LC_MESSAGES, languages/fr_FR, languages/it_IT/LC_MESSAGES/messages.mo, languages/it_IT/LC_MESSAGES, languages/it_IT, languages/ja_JP/LC_MESSAGES/messages.mo, languages/ja_JP/LC_MESSAGES, languages/ja_JP, languages/pt_BR/LC_MESSAGES/messages.mo, languages/pt_BR/LC_MESSAGES, languages/pt_BR, languages/ru_RU/LC_MESSAGES/messages.mo, languages/ru_RU/LC_MESSAGES, languages/ru_RU, languages/sv_SE/LC_MESSAGES/messages.mo, languages/sv_SE/LC_MESSAGES, languages/sv_SE, languages/tr_TR/LC_MESSAGES/messages.mo, languages/tr_TR/LC_MESSAGES, languages/tr_TR, languages/cs_CZ/LC_MESSAGES/messages.mo, languages/cs_CZ/LC_MESSAGES, languages/cs_CZ, languages/da_DK/LC_MESSAGES/messages.mo, languages/da_DK/LC_MESSAGES, languages/da_DK, languages/de_DE/LC_MESSAGES/messages.mo, languages/de_DE/LC_MESSAGES, languages/de_DE, languages/el_GR/LC_MESSAGES/messages.mo, languages/el_GR/LC_MESSAGES, languages/el_GR, languages/es_PY/LC_MESSAGES/messages.mo, languages/es_PY/LC_MESSAGES, languages/es_PY, languages/fi_FI/LC_MESSAGES/messages.mo, languages/fi_FI/LC_MESSAGES, languages/fi_FI, languages/fr_FR/LC_MESSAGES/messages.mo, languages/fr_FR/LC_MESSAGES, languages/fr_FR, languages/it_IT/LC_MESSAGES/messages.mo, languages/it_IT/LC_MESSAGES, languages/it_IT, languages/ja_JP/LC_MESSAGES/messages.mo, languages/ja_JP/LC_MESSAGES, languages/ja_JP, languages/pt_BR/LC_MESSAGES/messages.mo, languages/pt_BR/LC_MESSAGES, languages/pt_BR, languages/ru_RU/LC_MESSAGES/messages.mo, languages/ru_RU/LC_MESSAGES, languages/ru_RU, languages/sv_SE/LC_MESSAGES/messages.mo, languages/sv_SE/LC_MESSAGES, languages/sv_SE, languages/tr_TR/LC_MESSAGES/messages.mo, languages/tr_TR/LC_MESSAGES, languages/tr_TR

# concrete5 Cache Settings
Block Cache - On
Overrides Cache - On
Full Page Caching - Off
Full Page Cache Lifetime - Every 6 hours (default setting).

# Server Software
Apache

# Server API
cgi-fcgi

# PHP Version
5.6.29

# PHP Extensions
bcmath, bz2, calendar, cgi-fcgi, Core, ctype, curl, date, dom, ereg, exif, filter, ftp, gd, gettext, hash, iconv, imagick, imap, json, libxml, mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, openssl, pcntl, pcre, PDO, pdo_mysql, pdo_sqlite, Phar, posix, pspell, Reflection, session, SimpleXML, soap, sockets, SPL, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib.

# PHP Settings
max_execution_time - 30
log_errors_max_len - 1024
max_file_uploads - 20
max_input_nesting_level - 64
max_input_time - -1
max_input_vars - 1000
memory_limit - 90M
post_max_size - 65M
sql.safe_mode - Off
upload_max_filesize - 64M
mysql.max_links - Unlimited
mysql.max_persistent - Unlimited
mysqli.max_links - Unlimited
mysqli.max_persistent - Unlimited
pcre.backtrack_limit - 1000000
pcre.recursion_limit - 100000
session.cache_limiter - <i>no value</i>
session.gc_maxlifetime - 7200
soap.wsdl_cache_limit - 5

**Comment by Mesuva** [comment]
Have you tried using a release instead of manually firing off composer?
https://github.com/concrete5-community-store/community_store_stripe/releases/tag/v1.0.2

**Comment by jalen-seguin** [comment]
I'm not clear on how to proceed. I've already installed the community_store_stripe_master and run composer prior to telling c5 to install.  Do I need to undo the composer installation and the c5 installation and start fresh?

**Comment by Mesuva** [comment]
The folder name of the package should just be community_store_stripe.
Perhaps that's all that is going wrong here?

You don't need to do anything to undo composer, all that does is fetch a bunch of code and drop it into the package folder. So you can simply replace that folder with the release one.

**Comment by jalen-seguin** [comment]
Thanks for your help, however I already sorted out that issue and changed the name of the package to community_store_stripe.  

I (manually) uninstalled the package (removing a record from the Packages table).  I renamed the original community_store_stripe folder, and uploaded the release version instead.  Then I tried installing that package through c5.  This resulted in the following error message:
"Call to a member function getPackageHandle() on null"

This was the error message that I received when I first tried installing (before doing all sorts of research etc.)

**Comment by jalen-seguin** [comment]
When I try to view the package by going to Dashboard/Extend c5, I get the following error:
"Cannot redeclare class Concrete\Package\CommunityStoreStripe\Controller"

**Comment by Mesuva** [comment]
That sounds like you've got two copies of the package sitting in the packages folder.

**Comment by jalen-seguin** [comment]
I've got community_store and community_store_stripe.  Do I not need to install both?

**Comment by Mesuva** [comment]
Well you need to install community_store first, so yes, you need both.

But the error message about redeclaring the class suggests you've got two copies of the stripe package sitting in your packages folder.

**Comment by jalen-seguin** [comment]
I did have two stripe packages, named differently (community_store_stripe, community_store_stripe_old), but only had one installed.  I've since removed the "_old" version, and still the same problems occur.  I received this error on installation of community_store_stripe:
"Call to a member function getPackageHandle() on null'

c5 is still functional, but I get the above error every time I go to Dashboard/Store/Settings

**Comment by Mesuva** [comment]
I'd suggest turning on full debugging via /index.php/dashboard/system/environment/debug
It might help to see more clearly where this error is being thrown

I'm not having any trouble uninstalling and installing this particular add-on on my 5.7 install myself, so I can't really debug anything. I know others have used this version.

**Comment by jalen-seguin** [comment]
I uninstalled community_store_stripe.  Here's what showed up when I tried reinstalling it:

(error in line 164)
/home/jvk_admin/soulsexy.life/packages/community_store/src/CommunityStore/Payment/Method.php
 
        return $dir;
    }
 
    protected function setMethodController()
    {
        $th = Core::make("helper/text");
        $namespace = "Concrete\\Package\\" . $th->camelcase(Package::getByID($this->pkgID)->getPackageHandle()) . "\\Src\\CommunityStore\\Payment\\Methods\\" . $th->camelcase($this->pmHandle);
 
        $className = $th->camelcase($this->pmHandle) . "PaymentMethod";
(the last line is 164)

**Comment by Mesuva** [comment]
I think somewhere along the line where you had errors the record in CommunityStorePaymentMethods has been created wrong.

I'd suggest you remove community_store_stripe, then check the CommunityStorePaymentMethods table. If that has a record in that that references Stripe still, you'll need to delete that before trying to reinstall.

**Comment by jalen-seguin** [comment]
Removing that record did the trick.  Thanks!

**Comment by Mesuva** [comment]
Nice one!
